version: "3.0"
services:
  redis:
    image: redis:5-alpine
    ports:
      - "10002:6379"
  mongo:
    image: mongo:latest
    command: bash -c "mongod 2>&1 > xx.txt & sleep 7; tail -f xx.txt"
    volumes:
      - ./data/db_dev:/data/db
    ports:
      - "10001:27017"